os: linux
dist: bionic
services: docker
language: cpp
compiler:
  - gcc
  - clang
env:
  matrix:
    - CI_BUILD_TYPE="-DCMAKE_BUILD_TYPE=RELEASE -DCI_TEST_STORAGE_TYPE=v1direct"
    - CI_BUILD_TYPE="-DCMAKE_BUILD_TYPE=RELEASE -DCI_TEST_STORAGE_TYPE=v2merkle"
    - CI_BUILD_TYPE="-DCMAKE_BUILD_TYPE=DEBUG -DCI_TEST_STORAGE_TYPE=v2merkle"
script:
  - >
    script -q -e -c "make build \
                    CONCORD_BFT_CONTAINER_CC=${CC} CONCORD_BFT_CONTAINER_CXX=${CXX} \
                    CONCORD_BFT_CMAKE_FLAGS=\"\
                    ${CI_BUILD_TYPE} \
                    -DBUILD_TESTING=ON \
                    -DBUILD_COMM_TCP_PLAIN=FALSE \
                    -DBUILD_COMM_TCP_TLS=TRUE \
                    -DCMAKE_CXX_FLAGS_RELEASE=-O3 -g \
                    -DUSE_LOG4CPP=TRUE \
                    -DBUILD_ROCKSDB_STORAGE=TRUE \
                    -DUSE_S3_OBJECT_STORE=OFF \
                    -DUSE_OPENTRACING=ON \
                    -DOMIT_TEST_OUTPUT=ON\" "\
    && script -q -e -c "make test"
